### ISSUE TITLE
list of options not working

### ISSUE THREAD

**Issue by pdanpdan** [dubeg/theme-lp#3]
lp_always_show_minimap_viewport - looks like a duplicate of "always_show_minimap_viewport": true

lp_autohide_scrollbars - it looks like a duplicate of "overlay_scroll_bars": "enabled"

lp_hide_scrollbars - with "overlay_scroll_bars": "enabled") it has no effect

lp_hide_btn_close_tab - It seems that this option does not work. With it set to true or false the cross to close tabs shows on the active tab and on the mouse hovered tab.

**Comment by dubeg** [comment]
Ok, Im pushing the changes right now for these:
Hide scrollbar 
Hide close button
For the others:
Yes they are duplicated. Do you prefer not having them?

**Comment by pdanpdan** [comment]
i think it would be better not to be available - you would have to check in 2 places to see what's going on.
Thank you
