### ISSUE TITLE
Widget_VS not working

### ISSUE THREAD

**Issue by mikerockett** [dubeg/theme-lp#5]
Using ST3083, setting Widget_VS in `User/Widget - LP3.sublime-settings` does not work. Color scheme is always selected from User prefs - if I remove `color_scheme` from prefs, ST puts it back.

Any ideas?

**Comment by dubeg** [comment]
Depends what you are expecting to happen when setting the Widget color scheme.

Widgets are pointed with arrows in the screenshot below. This is where the widget color scheme is applied.
![demo-vs](https://cloud.githubusercontent.com/assets/6020602/11879462/794a5aaa-a4c9-11e5-9577-c0d81ecabd23.png)

Is this what is not working? Or are you trying to set the color scheme of the main editor?

EDIT: if you want the light Visual Studio color scheme, one that's very similar is available on PackageControl, named [Visual Studio Bold Color Scheme](https://github.com/Trismegistos84/visual-studio-bold). It's a fork with bolded keywords however.

**Comment by mikerockett** [comment]
You're totally correct - I'd read straight past that. Also did see the VS repo, but I prefer lighter colour schemes anyway.

Thanks for the clarification. :+1:
